// Synthetic 8 x 8 RGB/RGBA images encoded with Pillow; no personal data or metadata.
// Real containers keep successful handler tests independent of malformed input.

export const JPEG_BASE64 =
  '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcp' +
  'LDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIy' +
  'MjIyMjIyMjIyMjIyMjL/wAARCAAIAAgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAA' +
  'AgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6' +
  'Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXG' +
  'x8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREA' +
  'AgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5' +
  'OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPE' +
  'xcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwBxBgt4AI1Kyt5aBGZRCduGRDjgEBcsFG2M' +
  'A5ywFFFFc8686TSg90nu/wDM9LDUHLmjGbiou2lv8mf/2Q==';

export const PNG_BASE64 =
  'iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAIAAABLbSncAAAAgklEQVR4nGNg0Of1PHZlUuzs21+SVLo1c5U+bNu5/X9AHYPH' +
  'c9eJdTy3RC8rr5mV45y49ZbGv8L37hzbWDx2WHjs+O+xw8Jz+nEQYzqYveM4VMITzPfYAZLzBElbgCRALAiaDlILYYN1wAwB' +
  'qwBxPaESYEOg+kDSIC7cDrAFUE0gMwGo+GgJCZHf7wAAAABJRU5ErkJggg==';

export const WEBP_BASE64 =
  'UklGRowAAABXRUJQVlA4IIAAAABQAwCdASoIAAgAAUAmJbACdDKbvYa/WAmTX0AdDsW/PEgSwADxGlXPxoEaU0WyNYzkYvUj' +
  'PxZ6BT3vWJGiQs4HeQkh+yvn+xEI5oOiD+hE3+8w/QYFIQxJHoLMTihLLtj4Idben375ioNK8Jh/cf5y/8Cj/5UWBerm1+Zy' +
  'J8dgAA==';

export const WEBP_LOSSLESS_BASE64 =
  'UklGRi4BAABXRUJQVlA4TCIBAAAvB8ABAP/hNAAApMG9ujtE502uIhOdbc3dfW84DQBAiQ53SJrcEiOQWIExGcerO+8ujgMA' +
  'IKJs28azRWrn/s2As23f/McGAcoOJcGenjWBnknfFEWjNLR3oI7MXRD+qVCBVPv4YOYn8MBrrqgd+7c73L3Cue3/bSPBjl1K' +
  'uOAmVIYiIp/6D9cKIQDJ3RQBHkgN8PdP5sNPAI5qb4gMUL/vAfG7wNQGLCP4aoLdA7m4Rp5b9/jvwJcAIXcuIPenBdkIS5y2' +
  'o6/OrwRpkaY5p2TuSLvySDR7AhffaoXQ+J86xvlrFr2AQQAARKPZtm3biOh/JALgmbwYRieuMNxyBXQLd+icf+SG/ZJ8xw41' +
  'pE1h1ZDaPyVi6ITLguvxZpWtTfvoAw==';

export const WEBP_ALPHA_BASE64 =
  'UklGRrwAAABXRUJQVlA4WAoAAAAQAAAABwAABwAAQUxQSBgAAAABuYzof0BNAAKMFUT/nD4FIiZgAjB23QBWUDggfgAAAPAB' +
  'AJ0BKggACAABQCYlkAJ0MEYBZ7hPeAD+hRuzEd24TJJVzZ+ZTY1fPdGLYd505D1Jj/2STD/6R/0J/n/Prifyd9BZxrUXvPW1' +
  'L/LvUqbxL/lXKve5c/6YBD/2/L/WOH/BFb/xfuIT7f/geMf5LXv55Vzm005fwQiGpScAAA==';

// Tiny Pillow-generated progressive JPEG, no personal metadata.
export const JPEG_PROGRESSIVE_BASE64 = "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wgARCAAIAAgDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAT/xAAUAQEAAAAAAAAAAAAAAAAAAAAF/9oADAMBAAIQAxAAAAGQOC//xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAEFAn//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAEDAQE/AX//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAECAQE/AX//xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAY/An//xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAE/IX//2gAMAwEAAgADAAAAEPv/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAEDAQE/EH//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAECAQE/EH//xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAE/EH//2Q==";
