import 'fitness_recipe.dart';

/// Der englische Bestandskatalog der 30 eingebauten Rezepte.
///
/// Natürliche Küchen-Übersetzung von [recipeCatalogDe] (Inhalte-PR,
/// 2026-08-11) — KEINE Umrechnung von Mengen, nur Sprache: dieselben
/// Zahlen/Einheiten wie im deutschen Original, nur mit englischen
/// Zutaten-/Maßeinheitsbezeichnungen (TL → tsp, EL → tbsp; g/ml/cm bleiben).
/// Slug, `imageAsset`, Nährwerte und `categories` sind sprachneutrale
/// Identität und bewusst NICHT übersetzt — identisch zu [recipeCatalogDe],
/// Zeile für Zeile in derselben Reihenfolge (s.
/// `test/l10n/recipe_catalog_parity_test.dart`).
///
/// Diese Datei steht im Hartkodierungs-Wächter
/// (`test/l10n/hartkodierung_waechter_test.dart`) — sie MUSS englisch
/// bleiben.
const List<FitnessRecipe> recipeCatalogEn = <FitnessRecipe>[
  FitnessRecipe(
    slug: "hahnchen_mit_reis_and_brokkoli",
    title: "Chicken with Rice & Broccoli",
    description: "A classic lean-bulk or cutting plate with plenty of protein, easy-to-plan carbs, and a generous amount of vegetables.",
    portion: "1 large fitness plate / 1 main meal",
    ingredients: "- 180 g chicken breast fillet, raw\n- 75 g whole-grain rice or brown rice, raw\n- 220 g broccoli, fresh or frozen\n- 8 g olive oil\n- 1 tsp lemon juice\n- 1 small garlic clove, finely grated\n- 1/2 tsp sweet paprika powder\n- Salt, black pepper, parsley to taste",
    preparation: "1. Cook the rice in lightly salted water until tender and fluffy. Let it steam off briefly afterward.\n2. Rub the chicken with lemon juice, garlic, paprika, salt, pepper, and half the oil.\n3. Fry in a hot pan or grill pan for 4–5 minutes per side, until golden brown outside and juicy inside. Let rest for 3 minutes before slicing.\n4. Steam the broccoli or cook it in a little water, then season with the remaining oil, salt, and pepper.\n5. Plate in three clear sections: sliced chicken, a loose portion of rice, and the broccoli alongside.",
    professionalHint: "For meal prep, store the chicken and rice separately from the broccoli so it doesn't turn too soft when reheated.",
    imageAsset: "assets/recipes/hahnchen_mit_reis_and_brokkoli.jpg",
    caloriesKcal: 590,
    proteinG: 55,
    carbsG: 62,
    fatG: 12,
    estimatedGrams: 483,
    categories: <String>["High Protein", "Hauptgericht"],
  ),
  FitnessRecipe(
    slug: "lachs_mit_sukartoffel_and_spargel",
    title: "Salmon with Sweet Potato & Asparagus",
    description: "A protein-rich plate with omega-3 fats, complex carbs, and plenty of vegetables.",
    portion: "1 large fitness plate / 1 main meal",
    ingredients: "- 180 g salmon fillet\n- 300 g sweet potato, cut into wedges\n- 200 g green asparagus\n- 10 g olive oil\n- 1 tsp lemon juice\n- 1 tsp grainy mustard, optional\n- 1/2 tsp garlic powder\n- Salt, pepper, dill or parsley",
    preparation: "1. Toss the sweet potato wedges with half the oil, salt, pepper, and garlic powder. Roast at 200 °C top/bottom heat for 25–30 minutes.\n2. Trim the woody ends off the asparagus, season with a little oil, salt, and pepper, and add to the tray for the final 10–12 minutes.\n3. Pat the salmon dry and season with lemon juice, salt, pepper, and optionally a little mustard.\n4. Fry the salmon in a pan over medium heat, skin-side down first for 4 minutes, then flip and finish for 2–3 minutes.\n5. Plate it up: salmon in front, sweet potatoes to the side, asparagus as a green block in the background.",
    professionalHint: "For a lower-calorie version, use only 5 g of oil or reduce the sweet potato portion to 220 g.",
    imageAsset: "assets/recipes/lachs_mit_sukartoffel_and_spargel.jpg",
    caloriesKcal: 640,
    proteinG: 43,
    carbsG: 55,
    fatG: 29,
    estimatedGrams: 690,
    categories: <String>["Fisch", "High Protein"],
  ),
  FitnessRecipe(
    slug: "putensteak_mit_quinoa_and_ofengemuse",
    title: "Turkey Steak with Quinoa & Roasted Vegetables",
    description: "A very lean, protein-rich plate with quinoa and colorful vegetables for a modern fitness look.",
    portion: "1 large fitness plate / 1 main meal",
    ingredients: "- 200 g turkey breast steak, raw\n- 70 g quinoa, raw\n- 250 g roasted vegetables: zucchini, bell pepper, carrot\n- 10 g olive oil\n- 1 tsp lemon juice\n- 1/2 tsp paprika powder\n- 1/2 tsp Italian herbs\n- Salt, pepper, fresh parsley",
    preparation: "1. Rinse the quinoa thoroughly and simmer in double the amount of water for 12–15 minutes. Let it stand for 5 minutes afterward.\n2. Cut the vegetables into even pieces, toss with 6 g olive oil, salt, pepper, and herbs. Roast at 200 °C for about 20–25 minutes.\n3. Season the turkey steak with lemon juice, paprika, salt, pepper, and the remaining oil.\n4. Fry in a very hot grill pan for 3–5 minutes per side depending on thickness. Let rest briefly, then slice.\n5. Mound the quinoa loosely on the plate, lay the turkey strips alongside, and arrange the roasted vegetables colorfully next to it.",
    professionalHint: "Turkey dries out quickly. Don't fry it too long, and always let it rest briefly after cooking.",
    imageAsset: "assets/recipes/putensteak_mit_quinoa_and_ofengemuse.jpg",
    caloriesKcal: 610,
    proteinG: 58,
    carbsG: 57,
    fatG: 15,
    estimatedGrams: 530,
    categories: <String>["High Protein", "Hauptgericht"],
  ),
  FitnessRecipe(
    slug: "rindersteak_mit_kartoffeln_and_bohnen",
    title: "Beef Steak with Potatoes & Green Beans",
    description: "A hearty high-protein plate for a satisfying fitness meal with steak.",
    portion: "1 large fitness plate / 1 main meal",
    ingredients: "- 200 g lean beef steak, e.g. rump or sirloin\n- 280 g potatoes, waxy\n- 220 g green beans\n- 10 g olive oil\n- 1 small garlic clove\n- 1 sprig rosemary or 1/2 tsp dried\n- Salt, pepper, coarse chili flakes, optional",
    preparation: "1. Halve or quarter the potatoes, toss with 6 g oil, salt, pepper, and rosemary. Roast at 200 °C for 25–30 minutes.\n2. Blanch the beans in salted water for 5–7 minutes, then toss briefly in the pan with garlic and 2 g oil.\n3. Take the steak out of the fridge 30 minutes before frying, pat dry, and salt generously.\n4. Fry in a very hot pan with the remaining oil for 2–4 minutes per side depending on thickness. Pepper afterward and let rest for 5 minutes.\n5. Slice the steak and arrange it neatly separated from the potatoes and beans on the plate.",
    professionalHint: "For a cutting phase, choose a lean cut and trim visible fat. For muscle building, increase the potato portion.",
    imageAsset: "assets/recipes/rindersteak_mit_kartoffeln_and_bohnen.jpg",
    caloriesKcal: 670,
    proteinG: 52,
    carbsG: 48,
    fatG: 28,
    estimatedGrams: 710,
    categories: <String>["High Protein", "Hauptgericht"],
  ),
  FitnessRecipe(
    slug: "garnelen_mit_vollkornnudeln_and_zucchini",
    title: "Shrimp with Whole-Grain Pasta & Zucchini",
    description: "A light pasta plate with plenty of protein, a great sporty alternative to classic pasta.",
    portion: "1 large fitness plate / 1 main meal",
    ingredients: "- 200 g shrimp, peeled\n- 85 g whole-grain penne, raw\n- 250 g zucchini, in ribbons or slices\n- 8 g olive oil\n- 1 garlic clove, finely chopped\n- 1 tsp lemon juice\n- 1 tbsp chopped parsley\n- Salt, pepper, chili flakes, optional",
    preparation: "1. Cook the whole-grain pasta al dente and reserve 50 ml of the pasta water.\n2. Peel the zucchini into ribbons with a vegetable peeler, or cut into thin slices. Sauté briefly in 3 g oil so it stays firm to the bite.\n3. Pat the shrimp dry and season with salt, pepper, garlic, and lemon juice.\n4. Fry in a hot pan with the remaining oil for 1–2 minutes per side, until pink and juicy. Don't overcook.\n5. Toss the pasta with a little pasta water, parsley, and seasoning. Plate the shrimp, pasta, and zucchini in separate sections.",
    professionalHint: "If using pre-cooked shrimp, only heat them briefly or they'll turn rubbery. Keep the zucchini deliberately firm to the bite.",
    imageAsset: "assets/recipes/garnelen_mit_vollkornnudeln_and_zucchini.jpg",
    caloriesKcal: 560,
    proteinG: 48,
    carbsG: 68,
    fatG: 11,
    estimatedGrams: 543,
    categories: <String>["Fisch", "High Protein"],
  ),
  FitnessRecipe(
    slug: "omelett_mit_spinat_and_avocado",
    title: "Omelet with Spinach & Avocado",
    description: "A low-carb breakfast or dinner with realistic portion sizes, creamy avocado, and a big omelet.",
    portion: "1 large fitness plate / 1 main meal",
    ingredients: "- 3 whole eggs\n- 150 g egg whites, extra, for more protein and volume\n- 80 g fresh spinach\n- 80 g avocado, sliced\n- 120 g cherry tomatoes\n- 5 g olive oil or butter\n- 30 g grainy cream cheese or light feta, optional\n- Salt, pepper, chives",
    preparation: "1. Wilt the spinach briefly in a non-stick pan, season lightly with salt, and set aside.\n2. Whisk the eggs and egg whites with salt, pepper, and chives.\n3. Add oil or butter to the pan and let the egg mixture set over medium heat. Don't fry too hot so the omelet stays juicy.\n4. Add the spinach and optionally the cream cheese to one half, fold the omelet over, and finish briefly.\n5. Plate with avocado slices and halved cherry tomatoes.",
    professionalHint: "The combination of 3 eggs plus egg whites matches the omelet's visible size and delivers noticeably more protein than a small 1-egg omelet.",
    imageAsset: "assets/recipes/omelett_mit_spinat_and_avocado.jpg",
    caloriesKcal: 620,
    proteinG: 36,
    carbsG: 18,
    fatG: 44,
    estimatedGrams: 465,
    categories: <String>["Frühstück", "Low Carb"],
  ),
  FitnessRecipe(
    slug: "thunfisch_mit_couscous_and_gemuse",
    title: "Tuna with Couscous & Vegetables",
    description: "An elegant fitness plate with seared tuna, couscous, and colorful vegetables.",
    portion: "1 large fitness plate / 1 main meal",
    ingredients: "- 200 g tuna steak, very fresh\n- 80 g couscous, raw\n- 250 g vegetables: broccoli, zucchini, bell pepper\n- 8 g olive oil\n- 1 tsp lemon juice\n- 1 tsp soy sauce, optional\n- 1 tsp sesame seeds or cracked pepper crust, optional\n- Salt, pepper, parsley",
    preparation: "1. Pour hot vegetable broth over the couscous at a 1:1.2 ratio, cover, and let stand for 5–7 minutes. Then fluff with a fork.\n2. Cook the vegetables in a pan or the oven until firm to the bite, and season with salt, pepper, and a little oil.\n3. Pat the tuna dry, salt lightly, and optionally coat in pepper or sesame.\n4. Sear in a very hot pan with a little oil for just 45–75 seconds per side, so the center stays pink.\n5. Let rest briefly, slice evenly, and plate with couscous and colorful vegetables.",
    professionalHint: "Only use very fresh tuna. If you prefer it fully cooked, fry it longer, but you'll lose the juicy look.",
    imageAsset: "assets/recipes/thunfisch_mit_couscous_and_gemuse.jpg",
    caloriesKcal: 600,
    proteinG: 56,
    carbsG: 58,
    fatG: 15,
    estimatedGrams: 538,
    categories: <String>["Fisch", "High Protein"],
  ),
  FitnessRecipe(
    slug: "tofu_mit_reis_and_edamame",
    title: "Tofu with Rice & Edamame",
    description: "A vegan high-protein plate with crispy tofu, edamame, and rice.",
    portion: "1 large fitness plate / 1 main meal",
    ingredients: "- 200 g firm tofu, drained\n- 75 g rice, raw\n- 150 g edamame, shelled\n- 8 g sesame oil or neutral oil\n- 1 tbsp soy sauce\n- 1 tsp lime juice\n- 1 tsp maple syrup, optional\n- 1 tsp sesame seeds\n- Spring onion, pepper, chili, optional",
    preparation: "1. Cook the rice and let it steam off so it stays fluffy.\n2. Press the tofu well to remove moisture and cut into thick slices or rectangles.\n3. Mix soy sauce, lime juice, optionally maple syrup, and a little pepper. Marinate the tofu in it for 10 minutes.\n4. Fry the tofu in a hot non-stick pan with oil until golden brown on both sides.\n5. Heat the edamame in salted water for 3–5 minutes and drain.\n6. Plate the tofu, rice, and edamame clearly separated, and top with sesame seeds and spring onion.",
    professionalHint: "For more protein, use 250 g of tofu or plan an extra 100 g of soy yogurt dip on the side.",
    imageAsset: "assets/recipes/tofu_mit_reis_and_edamame.jpg",
    caloriesKcal: 610,
    proteinG: 35,
    carbsG: 78,
    fatG: 18,
    estimatedGrams: 433,
    categories: <String>["Vegetarisch", "Vegan", "High Protein"],
  ),
  FitnessRecipe(
    slug: "hahnchen_mit_sukartoffel_and_bohnen",
    title: "Chicken with Sweet Potato & Green Beans",
    description: "A meal-prep-friendly plate with lean chicken, roasted sweet potato, and green beans.",
    portion: "1 large fitness plate / 1 main meal",
    ingredients: "- 190 g chicken breast fillet, raw\n- 300 g sweet potato, diced\n- 220 g green beans\n- 10 g olive oil\n- 1/2 tsp paprika powder\n- 1/2 tsp garlic powder\n- 1 tsp lemon juice\n- Salt, pepper, parsley",
    preparation: "1. Toss the diced sweet potato with 6 g oil, paprika, garlic powder, salt, and pepper. Roast at 200 °C for 25–30 minutes.\n2. Blanch the beans for 5–7 minutes, then toss briefly in the pan.\n3. Season the chicken with lemon juice, salt, pepper, and a little oil.\n4. Fry in a grill pan until golden brown and cooked through but still juicy. Let rest for 3 minutes, then slice.\n5. Plate it up: chicken front left, sweet potatoes as an orange block, beans on the right.",
    professionalHint: "Great for 2–3 days of meal prep. When reheating, add a splash of water to the chicken to keep it juicy.",
    imageAsset: "assets/recipes/hahnchen_mit_sukartoffel_and_bohnen.jpg",
    caloriesKcal: 620,
    proteinG: 55,
    carbsG: 60,
    fatG: 16,
    estimatedGrams: 720,
    categories: <String>["High Protein", "Hauptgericht"],
  ),
  FitnessRecipe(
    slug: "putenballchen_mit_reis_and_gemuse",
    title: "Turkey Meatballs with Rice & Vegetables",
    description: "A family-friendly fitness dish with juicy turkey meatballs, rice, and vegetables.",
    portion: "1 large fitness plate / 1 main meal",
    ingredients: "- 220 g ground turkey, as lean as possible\n- 75 g rice, raw\n- 250 g vegetables: broccoli and carrots\n- 1 medium egg\n- 20 g fine oats\n- 1 small onion, very finely diced\n- 1 tsp mustard\n- 8 g olive oil\n- Salt, pepper, paprika, parsley",
    preparation: "1. Cook the rice and let it steam off.\n2. Mix the ground turkey with egg, oats, onion, mustard, salt, pepper, paprika, and parsley. Shape into 5–6 even meatballs.\n3. Fry the meatballs in a pan with oil, turning, for 8–10 minutes, or bake at 200 °C for 15–18 minutes in the oven.\n4. Steam or briefly boil the broccoli and carrots until firm to the bite and vibrant in color.\n5. Place the rice at the back of the plate, the meatballs in front, and the vegetables to the side.",
    professionalHint: "Oats and egg keep the meatballs juicy. For extra juiciness, add 1 tbsp of low-fat quark to the mixture.",
    imageAsset: "assets/recipes/putenballchen_mit_reis_and_gemuse.jpg",
    caloriesKcal: 650,
    proteinG: 55,
    carbsG: 65,
    fatG: 18,
    estimatedGrams: 573,
    categories: <String>["High Protein", "Hauptgericht"],
  ),
  FitnessRecipe(
    slug: "protein_pancakes_mit_beeren",
    title: "Protein Pancakes with Berries",
    description: "Fluffy high-protein pancakes with skyr and fresh berries as a power breakfast.",
    portion: "1 serving / 4–5 small pancakes",
    ingredients: "- 40 g fine oats\n- 2 whole eggs\n- 150 g low-fat quark or skyr\n- 1 small banana, about 90 g\n- 1 tsp baking powder\n- 100 g mixed berries\n- 1 tsp oil for the pan\n- Cinnamon, 1 tsp maple syrup, optional",
    preparation: "1. Blend the oats, eggs, quark, banana, baking powder, and cinnamon into a smooth batter.\n2. Heat a non-stick pan over medium heat with a little oil.\n3. Fry small pancakes, 1.5–2 minutes per side, until golden brown. Not too hot, or they'll darken outside while staying raw inside.\n4. Stack the pancakes, top with berries, and optionally drizzle with a little maple syrup.",
    professionalHint: "The banana adds natural sweetness — leave it out while dieting and use a bit of sweetener plus 10 g more oats instead.",
    imageAsset: "assets/recipes/protein_pancakes_mit_beeren.jpg",
    caloriesKcal: 500,
    proteinG: 37,
    carbsG: 58,
    fatG: 13,
    estimatedGrams: 470,
    categories: <String>["Frühstück", "High Protein", "Vegetarisch"],
  ),
  FitnessRecipe(
    slug: "overnight_oats_mit_skyr_and_banane",
    title: "Overnight Oats with Skyr & Banana",
    description: "A make-ahead high-protein breakfast to go, with oats, skyr, and banana.",
    portion: "1 jar / 1 breakfast serving",
    ingredients: "- 60 g oats\n- 150 g skyr or low-fat quark\n- 120 ml milk or soy drink\n- 1 tsp chia seeds\n- 1/2 banana, sliced\n- 80 g berries\n- 1 tsp honey or maple syrup\n- Cinnamon to taste",
    preparation: "1. Stir the oats, skyr, milk, chia seeds, and cinnamon together in a jar.\n2. Cover and refrigerate overnight, for at least 4 hours.\n3. Stir briefly in the morning, adding a splash of milk if needed.\n4. Top with banana slices, berries, and a drizzle of honey.",
    professionalHint: "Overnight, the oats swell up and turn creamy. The chia seeds also bind extra liquid and add fiber.",
    imageAsset: "assets/recipes/overnight_oats_mit_skyr_and_banane.jpg",
    caloriesKcal: 450,
    proteinG: 30,
    carbsG: 62,
    fatG: 9,
    estimatedGrams: 470,
    categories: <String>["Frühstück", "Vegetarisch", "High Protein"],
  ),
  FitnessRecipe(
    slug: "skyr_bowl_mit_beeren_and_granola",
    title: "Skyr Bowl with Berries & Granola",
    description: "A creamy high-protein bowl with Icelandic skyr, fresh berries, and crunchy granola.",
    portion: "1 bowl / 1 breakfast serving",
    ingredients: "- 250 g plain skyr\n- 40 g granola or crunchy muesli\n- 120 g mixed berries\n- 10 g nuts, roughly chopped\n- 1 tsp honey\n- 1 tsp flaxseed, optional",
    preparation: "1. Stir the skyr smooth and spoon it into a bowl.\n2. Wash the berries and spread them over the skyr.\n3. Sprinkle with granola and chopped nuts.\n4. Finish with a drizzle of honey and optionally flaxseed.",
    professionalHint: "Add the granola just before eating so it stays crunchy. Choose an unsweetened granola for less sugar.",
    imageAsset: "assets/recipes/skyr_bowl_mit_beeren_and_granola.jpg",
    caloriesKcal: 430,
    proteinG: 38,
    carbsG: 48,
    fatG: 9,
    estimatedGrams: 420,
    categories: <String>["Frühstück", "High Protein", "Vegetarisch"],
  ),
  FitnessRecipe(
    slug: "shakshuka_mit_eiern_and_feta",
    title: "Shakshuka with Eggs & Feta",
    description: "A spicy tomato-pepper skillet with poached eggs and feta — high in protein and low carb.",
    portion: "1 pan / 1 large serving",
    ingredients: "- 3 eggs\n- 400 g strained tomatoes\n- 1 red bell pepper, in strips\n- 1/2 onion\n- 1 garlic clove\n- 40 g feta\n- 8 g olive oil\n- 1 tsp paprika powder, 1/2 tsp cumin\n- Salt, pepper, parsley",
    preparation: "1. Sauté the onion and bell pepper in oil until translucent, then briefly toast the garlic and spices.\n2. Add the strained tomatoes and simmer for 8–10 minutes, season with salt and pepper.\n3. Use a spoon to make three wells in the sauce and slide an egg into each.\n4. Cover and poach for 6–8 minutes, until the whites are set but the yolks are still creamy.\n5. Sprinkle with crumbled feta and parsley and serve straight from the pan.",
    professionalHint: "The yolk should still be slightly runny. It's better to take it off the heat a bit early — it keeps cooking afterward.",
    imageAsset: "assets/recipes/shakshuka_mit_eiern_and_feta.jpg",
    caloriesKcal: 480,
    proteinG: 28,
    carbsG: 22,
    fatG: 30,
    estimatedGrams: 600,
    categories: <String>["Frühstück", "Vegetarisch", "Low Carb"],
  ),
  FitnessRecipe(
    slug: "ruhrei_mit_vollkornbrot_and_avocado",
    title: "Scrambled Eggs with Whole-Grain Bread & Avocado",
    description: "A filling breakfast with creamy scrambled eggs, avocado, and whole-grain bread.",
    portion: "1 plate / 1 breakfast serving",
    ingredients: "- 3 eggs\n- 1 slice whole-grain bread, about 50 g\n- 70 g avocado\n- 100 g cherry tomatoes\n- 5 g butter or oil\n- 1 tbsp milk\n- Salt, pepper, chives",
    preparation: "1. Whisk the eggs with milk, salt, and pepper.\n2. Melt the butter in a pan over low heat, add the eggs, and let them set slowly into creamy scrambled eggs — stirring gently the whole time.\n3. Toast the whole-grain bread.\n4. Lay avocado on the toast, sliced or roughly mashed, and salt lightly.\n5. Plate the scrambled eggs, avocado toast, and halved cherry tomatoes, and sprinkle with chives.",
    professionalHint: "Cook the scrambled eggs over low heat and take them off early — that keeps them creamy instead of dry.",
    imageAsset: "assets/recipes/ruhrei_mit_vollkornbrot_and_avocado.jpg",
    caloriesKcal: 540,
    proteinG: 28,
    carbsG: 34,
    fatG: 31,
    estimatedGrams: 380,
    categories: <String>["Frühstück", "Vegetarisch", "High Protein"],
  ),
  FitnessRecipe(
    slug: "chicken_wrap_mit_joghurt_dressing",
    title: "Chicken Wrap with Yogurt Dressing",
    description: "A handy high-protein wrap with chicken, crisp vegetables, and a light yogurt dressing.",
    portion: "1 large wrap",
    ingredients: "- 160 g chicken breast fillet\n- 1 whole-grain tortilla, about 65 g\n- 60 g iceberg lettuce\n- 1/2 tomato, 1/4 cucumber\n- 60 g Greek yogurt, 2%\n- 1 tsp mustard, 1 tsp lemon juice\n- 6 g oil\n- Salt, pepper, paprika",
    preparation: "1. Cut the chicken into strips, season with salt, pepper, and paprika, and fry in oil until golden brown.\n2. For the dressing, stir together yogurt, mustard, lemon juice, salt, and pepper.\n3. Warm the tortilla briefly in a dry pan so it becomes pliable.\n4. Layer lettuce, tomato, cucumber, and chicken in the center, and drizzle with the dressing.\n5. Fold in the sides and roll up tightly. Halve and serve.",
    professionalHint: "Don't overfill the wrap or the tortilla will tear. The yogurt dressing saves a lot of calories compared to mayo.",
    imageAsset: "assets/recipes/chicken_wrap_mit_joghurt_dressing.jpg",
    caloriesKcal: 560,
    proteinG: 48,
    carbsG: 52,
    fatG: 16,
    estimatedGrams: 380,
    categories: <String>["Hauptgericht", "High Protein"],
  ),
  FitnessRecipe(
    slug: "hahnchen_curry_mit_reis",
    title: "Chicken Curry with Rice",
    description: "A creamy curry with tender chicken pieces, a light coconut note, and rice.",
    portion: "1 large serving",
    ingredients: "- 180 g chicken breast fillet, diced\n- 80 g rice, raw\n- 100 ml light coconut milk\n- 100 g strained tomatoes\n- 1/2 onion, 1 garlic clove\n- 100 g bell pepper\n- 8 g oil\n- 1 tbsp curry paste or curry powder\n- Salt, cilantro or parsley",
    preparation: "1. Cook the rice and keep it warm.\n2. Sauté the onion and garlic in oil, briefly toast the curry paste.\n3. Add the diced chicken and sear on all sides.\n4. Add the bell pepper, strained tomatoes, and coconut milk, and simmer for 10–12 minutes, until the chicken is cooked through and the sauce is thick.\n5. Season with salt and serve with rice and fresh cilantro.",
    professionalHint: "Light coconut milk saves fat without losing all the creaminess. For more heat, add a bit of chili or ginger.",
    imageAsset: "assets/recipes/hahnchen_curry_mit_reis.jpg",
    caloriesKcal: 640,
    proteinG: 50,
    carbsG: 70,
    fatG: 16,
    estimatedGrams: 560,
    categories: <String>["Hauptgericht", "High Protein"],
  ),
  FitnessRecipe(
    slug: "rinderhack_chili_mit_bohnen",
    title: "Ground Beef Chili with Beans",
    description: "A hearty chili con carne with lean ground beef, kidney beans, and corn — perfect for batch cooking.",
    portion: "1 large bowl",
    ingredients: "- 180 g lean ground beef\n- 120 g kidney beans, cooked\n- 80 g corn\n- 200 g strained tomatoes\n- 1/2 onion, 1 garlic clove\n- 1/2 bell pepper\n- 8 g oil\n- 1 tsp paprika powder, 1/2 tsp cumin, chili\n- Salt, pepper",
    preparation: "1. Sauté the onion, garlic, and bell pepper in oil.\n2. Add the ground beef and fry, breaking it up, until it takes on color.\n3. Briefly toast the spices, then add the strained tomatoes, beans, and corn.\n4. Simmer for 15–20 minutes, stirring occasionally, and season with salt and pepper.\n5. Serve in a bowl, optionally with a little yogurt and cilantro.",
    professionalHint: "The longer the chili simmers, the rounder the flavor. It often tastes even better the next day — ideal for meal prep.",
    imageAsset: "assets/recipes/rinderhack_chili_mit_bohnen.jpg",
    caloriesKcal: 600,
    proteinG: 47,
    carbsG: 52,
    fatG: 22,
    estimatedGrams: 620,
    categories: <String>["Hauptgericht", "High Protein"],
  ),
  FitnessRecipe(
    slug: "rinderstreifen_stir_fry_mit_reis",
    title: "Beef Strip Stir-Fry with Rice",
    description: "A quick wok plate with tender beef strips, crisp vegetables, and rice in soy sauce.",
    portion: "1 large serving",
    ingredients: "- 180 g lean beef, in strips\n- 80 g rice, raw\n- 200 g stir-fry vegetables: broccoli, bell pepper, carrot, snow peas\n- 8 g oil\n- 1.5 tbsp soy sauce\n- 1 tsp sesame oil, 1 tsp honey\n- 1 cm ginger, 1 garlic clove\n- Sesame seeds, spring onion",
    preparation: "1. Cook the rice and keep it warm.\n2. Sear the beef strips in very hot oil for 1–2 minutes and remove.\n3. Stir-fry the vegetables in the same wok for 3–4 minutes until firm to the bite, add ginger and garlic.\n4. Return the beef to the wok, deglaze with soy sauce, sesame oil, and honey, and toss briefly.\n5. Serve over rice, sprinkled with sesame seeds and spring onion.",
    professionalHint: "Get the wok really hot and sear the meat in batches — that way it sears instead of boiling.",
    imageAsset: "assets/recipes/rinderstreifen_stir_fry_mit_reis.jpg",
    caloriesKcal: 620,
    proteinG: 45,
    carbsG: 62,
    fatG: 18,
    estimatedGrams: 520,
    categories: <String>["Hauptgericht", "High Protein"],
  ),
  FitnessRecipe(
    slug: "schweinefilet_mit_kartoffeln_and_brokkoli",
    title: "Pork Tenderloin with Potatoes & Broccoli",
    description: "Lean pork tenderloin with roasted potatoes and broccoli — plenty of protein with moderate fat.",
    portion: "1 large fitness plate",
    ingredients: "- 200 g pork tenderloin\n- 280 g potatoes, waxy\n- 220 g broccoli\n- 10 g olive oil\n- 1 garlic clove\n- 1/2 tsp thyme\n- Salt, pepper, mustard, optional",
    preparation: "1. Cut the potatoes into wedges, toss with 6 g oil, salt, pepper, and thyme, and roast at 200 °C for 25–30 minutes.\n2. Pat the pork tenderloin dry, salt it, and sear on all sides in a hot pan with the remaining oil.\n3. Finish in the oven at 180 °C for 8–10 minutes, until the internal temperature reaches about 62 °C. Then let rest.\n4. Steam the broccoli until firm to the bite.\n5. Slice the tenderloin into medallions and plate with potatoes and broccoli.",
    professionalHint: "Pork tenderloin is very lean and cooks through quickly. Work with an internal thermometer and let it rest — that keeps it juicy.",
    imageAsset: "assets/recipes/schweinefilet_mit_kartoffeln_and_brokkoli.jpg",
    caloriesKcal: 580,
    proteinG: 52,
    carbsG: 50,
    fatG: 18,
    estimatedGrams: 600,
    categories: <String>["Hauptgericht", "High Protein"],
  ),
  FitnessRecipe(
    slug: "hahnchen_pesto_pasta",
    title: "Chicken Pesto Pasta",
    description: "Creamy pasta with chicken and pesto — filling and protein-rich for after training.",
    portion: "1 large serving",
    ingredients: "- 170 g chicken breast fillet\n- 90 g whole-grain pasta, raw\n- 30 g pesto\n- 100 g cherry tomatoes\n- 50 g spinach\n- 20 g parmesan\n- 6 g oil\n- Salt, pepper",
    preparation: "1. Cook the pasta al dente and reserve a little pasta water.\n2. Cut the chicken into strips, season, and fry in oil until golden brown.\n3. Halve the cherry tomatoes and add briefly, then add the spinach and let it wilt.\n4. Toss the pasta, chicken, pesto, and a little pasta water together until a creamy sauce forms.\n5. Serve with shaved parmesan and pepper.",
    professionalHint: "Pesto is calorie-dense — weigh the 30 g deliberately. A little pasta water makes the sauce creamy without needing more oil.",
    imageAsset: "assets/recipes/hahnchen_pesto_pasta.jpg",
    caloriesKcal: 660,
    proteinG: 50,
    carbsG: 66,
    fatG: 22,
    estimatedGrams: 480,
    categories: <String>["Hauptgericht", "High Protein"],
  ),
  FitnessRecipe(
    slug: "hahnchen_caesar_salat",
    title: "Chicken Caesar Salad",
    description: "A crisp Caesar salad with grilled chicken and a light yogurt dressing — protein-rich and low carb.",
    portion: "1 large salad bowl",
    ingredients: "- 180 g chicken breast fillet\n- 120 g romaine lettuce\n- 60 g Greek yogurt, 2%\n- 15 g parmesan\n- 1 tsp mustard, 1 tsp lemon juice, 1 anchovy, optional\n- 20 g whole-grain croutons\n- 6 g oil\n- Salt, pepper",
    preparation: "1. Season the chicken and fry in oil until golden brown, then cut into strips.\n2. For the dressing, stir together yogurt, mustard, lemon juice, finely chopped anchovy, a little parmesan, salt, and pepper.\n3. Wash the romaine lettuce, spin dry, and tear into bite-sized pieces.\n4. Toss the lettuce with the dressing and top with the chicken strips.\n5. Top with parmesan and a few croutons.",
    professionalHint: "Classic Caesar dressing is high in fat and calories. The yogurt version brings the creaminess with far less fat.",
    imageAsset: "assets/recipes/hahnchen_caesar_salat.jpg",
    caloriesKcal: 470,
    proteinG: 50,
    carbsG: 18,
    fatG: 22,
    estimatedGrams: 420,
    categories: <String>["Hauptgericht", "High Protein", "Low Carb"],
  ),
  FitnessRecipe(
    slug: "thunfisch_vollkornpasta",
    title: "Tuna Whole-Grain Pasta",
    description: "A quick protein pasta with tuna, tomato sauce, and whole-grain noodles — no fuss required.",
    portion: "1 large serving",
    ingredients: "- 150 g canned tuna, in its own juice\n- 90 g whole-grain pasta, raw\n- 200 g strained tomatoes\n- 1/2 onion, 1 garlic clove\n- 50 g peas\n- 6 g olive oil\n- 1 tsp herbs, chili, optional\n- Salt, pepper, parsley",
    preparation: "1. Cook the pasta al dente.\n2. Sauté the onion and garlic in oil, add the strained tomatoes, and simmer for 8 minutes.\n3. Fold in the peas and drained tuna and warm through briefly.\n4. Season with salt, pepper, and herbs.\n5. Toss the pasta with the sauce and serve with parsley.",
    professionalHint: "Tuna in its own juice saves fat and calories compared to oil. Add it at the end so it doesn't fall apart.",
    imageAsset: "assets/recipes/thunfisch_vollkornpasta.jpg",
    caloriesKcal: 600,
    proteinG: 45,
    carbsG: 72,
    fatG: 13,
    estimatedGrams: 470,
    categories: <String>["Fisch", "High Protein"],
  ),
  FitnessRecipe(
    slug: "kabeljau_mit_kartoffelpuree_and_erbsen",
    title: "Cod with Mashed Potatoes & Peas",
    description: "Lean cod over creamy mashed potatoes with peas — light and protein-rich.",
    portion: "1 large fitness plate",
    ingredients: "- 200 g cod fillet\n- 280 g potatoes, floury\n- 100 g peas\n- 60 ml milk\n- 10 g butter\n- 1 tsp lemon juice\n- 6 g oil\n- Salt, pepper, dill",
    preparation: "1. Peel the potatoes, boil in salted water until soft, drain, and mash with milk and butter into a creamy purée.\n2. Boil or steam the peas briefly.\n3. Pat the cod dry and season with salt, pepper, and lemon juice.\n4. Fry in a pan with a little oil over medium heat for 2–3 minutes per side, until the fillet is opaque and just cooked through.\n5. Spoon the purée onto the plate, place the cod on top, add the peas alongside, and sprinkle with dill.",
    professionalHint: "Cod is very delicate and falls apart easily. Turn it only once and don't fry it too long.",
    imageAsset: "assets/recipes/kabeljau_mit_kartoffelpuree_and_erbsen.jpg",
    caloriesKcal: 520,
    proteinG: 44,
    carbsG: 50,
    fatG: 12,
    estimatedGrams: 640,
    categories: <String>["Fisch", "High Protein"],
  ),
  FitnessRecipe(
    slug: "lachs_poke_bowl",
    title: "Salmon Poke Bowl",
    description: "A fresh poke bowl with salmon, rice, edamame, and avocado, Hawaiian style.",
    portion: "1 large bowl",
    ingredients: "- 150 g salmon fillet, very fresh, diced\n- 90 g sushi rice or brown rice, raw\n- 60 g edamame\n- 60 g avocado\n- 60 g cucumber, 60 g carrot\n- 1.5 tbsp soy sauce, 1 tsp sesame oil, 1 tsp lime juice\n- Sesame seeds, spring onion, nori, optional",
    preparation: "1. Cook the rice and add it lukewarm to the bowl.\n2. Marinate the diced salmon in soy sauce, sesame oil, and lime juice for 10 minutes.\n3. Briefly boil the edamame, and cut the cucumber, carrot, and avocado into strips or cubes.\n4. Arrange all the components in sections over the rice.\n5. Drizzle with sesame seeds, spring onion, and a little of the marinade.",
    professionalHint: "Only use sushi-grade, very fresh salmon raw. If you'd rather avoid raw fish, sear the cubes briefly and hot.",
    imageAsset: "assets/recipes/lachs_poke_bowl.jpg",
    caloriesKcal: 620,
    proteinG: 40,
    carbsG: 65,
    fatG: 20,
    estimatedGrams: 540,
    categories: <String>["Fisch", "High Protein"],
  ),
  FitnessRecipe(
    slug: "linsen_dal_mit_reis",
    title: "Red Lentil Dal with Rice",
    description: "A warming vegan dal made from red lentils with rice — protein-rich, high in fiber, and budget-friendly.",
    portion: "1 large bowl",
    ingredients: "- 100 g red lentils, raw\n- 80 g rice, raw\n- 100 g strained tomatoes\n- 1/2 onion, 1 garlic clove, 1 cm ginger\n- 100 ml light coconut milk\n- 8 g oil\n- 1 tsp curry powder, 1/2 tsp turmeric, 1/2 tsp cumin\n- Salt, cilantro, lime",
    preparation: "1. Cook the rice and keep it warm.\n2. Sauté the onion, garlic, and ginger in oil, briefly toast the spices.\n3. Add the lentils, strained tomatoes, coconut milk, and 200 ml water.\n4. Simmer for 15–18 minutes, until the lentils are soft and the dal turns thick. Stir occasionally.\n5. Season with salt and lime juice and serve with rice and cilantro.",
    professionalHint: "Red lentils need no soaking and break down into a creamy texture. They deliver plenty of plant protein and fiber.",
    imageAsset: "assets/recipes/linsen_dal_mit_reis.jpg",
    caloriesKcal: 560,
    proteinG: 26,
    carbsG: 88,
    fatG: 10,
    estimatedGrams: 560,
    categories: <String>["Vegetarisch", "Vegan", "High Protein", "Hauptgericht"],
  ),
  FitnessRecipe(
    slug: "kichererbsen_curry_mit_reis",
    title: "Chickpea Curry with Rice",
    description: "A filling vegan chana curry with chickpeas, tomatoes, and rice.",
    portion: "1 large bowl",
    ingredients: "- 200 g chickpeas, cooked\n- 80 g rice, raw\n- 200 g strained tomatoes\n- 1/2 onion, 1 garlic clove, 1 cm ginger\n- 80 g spinach\n- 8 g oil\n- 1 tbsp curry powder, 1/2 tsp garam masala\n- Salt, cilantro",
    preparation: "1. Cook the rice and keep it warm.\n2. Sauté the onion, garlic, and ginger in oil, briefly toast the spices.\n3. Add the strained tomatoes and chickpeas and simmer for 12–15 minutes.\n4. Stir in the spinach and let it wilt, season with salt.\n5. Serve with rice and fresh cilantro.",
    professionalHint: "Rinse canned chickpeas well. For a creamier result, add a splash of coconut milk or a little soy yogurt.",
    imageAsset: "assets/recipes/kichererbsen_curry_mit_reis.jpg",
    caloriesKcal: 580,
    proteinG: 22,
    carbsG: 92,
    fatG: 12,
    estimatedGrams: 580,
    categories: <String>["Vegetarisch", "Vegan", "Hauptgericht"],
  ),
  FitnessRecipe(
    slug: "falafel_bowl_mit_hummus",
    title: "Falafel Bowl with Hummus",
    description: "A vegan mezze bowl with crispy falafel, hummus, quinoa, and fresh vegetables.",
    portion: "1 large bowl",
    ingredients: "- 5 falafel balls, about 120 g\n- 60 g quinoa, raw\n- 50 g hummus\n- 80 g cucumber, 100 g cherry tomatoes\n- 40 g red cabbage\n- 1 tsp lemon juice, parsley\n- Salt, pepper",
    preparation: "1. Rinse and cook the quinoa, then let it stand.\n2. Bake the falafel crispy in the oven or pan following the package instructions.\n3. Cut the cucumber, tomatoes, and red cabbage into bite-sized pieces.\n4. Add the quinoa as a base to the bowl, and arrange the falafel, vegetables, and a spoonful of hummus on top.\n5. Finish with lemon juice, parsley, salt, and pepper.",
    professionalHint: "Oven-baked falafel instead of fried saves a lot of fat. Hummus adds extra plant protein and makes the bowl creamy.",
    imageAsset: "assets/recipes/falafel_bowl_mit_hummus.jpg",
    caloriesKcal: 600,
    proteinG: 22,
    carbsG: 70,
    fatG: 26,
    estimatedGrams: 520,
    categories: <String>["Vegetarisch", "Vegan"],
  ),
  FitnessRecipe(
    slug: "tempeh_stir_fry_mit_reis",
    title: "Tempeh Stir-Fry with Rice",
    description: "A vegan wok dish with protein-rich tempeh, crisp vegetables, and rice in a spicy soy sauce.",
    portion: "1 large serving",
    ingredients: "- 160 g tempeh, diced\n- 80 g rice, raw\n- 200 g stir-fry vegetables: broccoli, bell pepper, carrot\n- 8 g oil\n- 1.5 tbsp soy sauce, 1 tsp sesame oil, 1 tsp maple syrup\n- 1 garlic clove, 1 cm ginger\n- Sesame seeds, spring onion",
    preparation: "1. Cook the rice and keep it warm.\n2. Fry the diced tempeh in hot oil until golden brown all over and remove.\n3. Stir-fry the vegetables in the wok for 3–4 minutes until firm to the bite, add garlic and ginger.\n4. Return the tempeh, deglaze with soy sauce, sesame oil, and maple syrup, and toss briefly.\n5. Serve over rice, sprinkled with sesame seeds and spring onion.",
    professionalHint: "Briefly steaming or blanching the tempeh before frying removes the slight bitterness and makes it juicier.",
    imageAsset: "assets/recipes/tempeh_stir_fry_mit_reis.jpg",
    caloriesKcal: 600,
    proteinG: 34,
    carbsG: 66,
    fatG: 20,
    estimatedGrams: 500,
    categories: <String>["Vegetarisch", "Vegan", "High Protein", "Hauptgericht"],
  ),
  FitnessRecipe(
    slug: "halloumi_avocado_bowl",
    title: "Halloumi Avocado Bowl",
    description: "A vegetarian low-carb bowl with fried halloumi, avocado, and a colorful salad.",
    portion: "1 large bowl",
    ingredients: "- 100 g halloumi\n- 80 g avocado\n- 120 g mixed greens and arugula\n- 100 g cherry tomatoes\n- 60 g cucumber\n- 30 g chickpeas, cooked\n- 1 tsp olive oil, 1 tsp lemon juice\n- Salt, pepper, mint, optional",
    preparation: "1. Slice the halloumi and fry in a dry or lightly oiled pan until golden brown on both sides.\n2. Put the greens, halved cherry tomatoes, and cucumber in a bowl.\n3. Slice the avocado and add it in, then sprinkle with chickpeas.\n4. Dress with olive oil, lemon juice, salt, and pepper.\n5. Arrange the warm halloumi on top, optionally with a little mint.",
    professionalHint: "Halloumi is naturally salty and rich in fat — weigh the 100 g deliberately. It also stays pleasantly firm to the bite when warm.",
    imageAsset: "assets/recipes/halloumi_avocado_bowl.jpg",
    caloriesKcal: 560,
    proteinG: 28,
    carbsG: 24,
    fatG: 38,
    estimatedGrams: 520,
    categories: <String>["Vegetarisch", "Low Carb"],
  ),
];
