// Byte-exact slot values of a build from #70 (3b50178), the only release that
// wrote schema v1 recovery checkpoints. Generated by running that commit's
// unmodified lib/src/models (TrainingSessionSnapshot.toJson v1 and
// TrainingPlan.toRow without exercise identities) through the encoding of its
// LocalCache.writeTrainingSession and writeTrainingPlans:
//   jsonEncode({'snapshot': checkpoint.toJson()})
//   jsonEncode({'items': [plan.toRow()]})
// The workout was paused in the rest after the first logged Squat set.

const legacyPlanId = 'coach_legacy-message';

const legacyCheckpointSlot =
    '{"snapshot":{"schema_version":1,"status":"paused","plan":{"id":'
    '"coach_legacy-message","plan":{"schema_version":1,"title":"Strength",'
    '"description":"","goal":"Build strength","workouts":[{"title":"Day A",'
    '"description":"","exercises":[{"name":"Squat","sets":2,"reps":8,'
    '"duration_seconds":null,"rest_seconds":60,"notes":""},{"name":"Plank",'
    '"sets":1,"reps":null,"duration_seconds":30,"rest_seconds":0,'
    '"notes":"Brace."}]}]}},"workout_index":0,"exercise_index":0,'
    '"set_index":0,"phase":"rest","remaining_milliseconds":42000,'
    '"completed_sets":[{"exercise_index":0,"set_index":0}],"skipped_sets":[]}}';

const legacyPlanLibrarySlot =
    '{"items":[{"id":"coach_legacy-message","plan":{"schema_version":1,'
    '"title":"Strength","description":"","goal":"Build strength","workouts":'
    '[{"title":"Day A","description":"","exercises":[{"name":"Squat","sets":2,'
    '"reps":8,"duration_seconds":null,"rest_seconds":60,"notes":""},'
    '{"name":"Plank","sets":1,"reps":null,"duration_seconds":30,'
    '"rest_seconds":0,"notes":"Brace."}]}]}}]}';
