"""Generates the native launch marks from the focus-ring geometry.

The Flutter welcome screen's first frame shows the focus ring alone, 80
logical px, centred on the full screen, in the dark accent on the dark page
ground (`WelcomeScreen`, `paintFocusRing`). The native launch screens draw the
identical mark, so the hand-off from native splash to Flutter shows no change.

Writes (run from the project root, needs Pillow):
  android/app/src/main/res/drawable/launch_mark.xml         80 dp vector
  android/app/src/main/res/drawable/launch_splash_icon.xml  288 dp vector for
      the Android 12+ splash API (icon without background: 288 dp canvas,
      content inside the 192 dp circle, drawn 1:1 in dp)
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage{,@2x,@3x}.png

Ratios mirror `paintFocusRing` in lib/src/widgets/shared/eatova_wordmark.dart;
change both together.
"""

from pathlib import Path

from PIL import Image, ImageDraw

BOX = 80.0  # logical px / dp / pt
COLOR = "#B9A5FF"  # AppTokens.dark.accent
RGB = (0xB9, 0xA5, 0xFF)


def geometry(box):
    stroke = box * 0.105
    tick = box * 0.115
    gap = box * 0.075
    ring_r = box / 2 - tick - gap - stroke / 2
    dot_r = box * 0.10
    inner = ring_r + stroke / 2 + gap
    return stroke, tick, ring_r, dot_r, inner


def f(v):
    return f"{v:.3f}".rstrip("0").rstrip(".")


def vector(size, comment):
    stroke, tick, ring_r, dot_r, inner = geometry(BOX)
    c = size / 2
    h = stroke / 2
    ticks = []
    for dx, dy in ((0, -1), (1, 0), (0, 1), (-1, 0)):
        if dx == 0:
            y0, y1 = sorted((c + dy * inner, c + dy * (inner + tick)))
            ticks.append(f"M{f(c - h)},{f(y0)}H{f(c + h)}V{f(y1)}H{f(c - h)}Z")
        else:
            x0, x1 = sorted((c + dx * inner, c + dx * (inner + tick)))
            ticks.append(f"M{f(x0)},{f(c - h)}H{f(x1)}V{f(c + h)}H{f(x0)}Z")

    def circle(r):
        return (
            f"M{f(c - r)},{f(c)}a{f(r)},{f(r)} 0 1,0 {f(2 * r)},0"
            f"a{f(r)},{f(r)} 0 1,0 {f(-2 * r)},0Z"
        )

    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- {comment}
     Generated by tool/launch_mark.py from the focus-ring geometry; do not
     edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{f(size)}dp"
    android:height="{f(size)}dp"
    android:viewportWidth="{f(size)}"
    android:viewportHeight="{f(size)}">
    <path
        android:pathData="{circle(ring_r)}"
        android:strokeColor="@color/launch_mark"
        android:strokeWidth="{f(stroke)}" />
    <path
        android:fillColor="@color/launch_mark"
        android:pathData="{circle(dot_r)}{''.join(ticks)}" />
</vector>
"""


def png(scale):
    ss = 8  # supersampling
    px = int(BOX * scale)
    big = px * ss
    k = scale * ss
    stroke, tick, ring_r, dot_r, inner = geometry(BOX)
    mask = Image.new("L", (big, big), 0)
    d = ImageDraw.Draw(mask)
    c = big / 2
    ro, ri = (ring_r + stroke / 2) * k, (ring_r - stroke / 2) * k
    d.ellipse((c - ro, c - ro, c + ro, c + ro), fill=255)
    d.ellipse((c - ri, c - ri, c + ri, c + ri), fill=0)
    r = dot_r * k
    d.ellipse((c - r, c - r, c + r, c + r), fill=255)
    h = stroke / 2 * k
    a, b = inner * k, (inner + tick) * k
    d.rectangle((c - h, c - b, c + h, c - a), fill=255)
    d.rectangle((c - h, c + a, c + h, c + b), fill=255)
    d.rectangle((c - b, c - h, c - a, c + h), fill=255)
    d.rectangle((c + a, c - h, c + b, c + h), fill=255)
    mask = mask.resize((px, px), Image.LANCZOS)
    img = Image.new("RGBA", (px, px), RGB + (0,))
    img.putalpha(mask)
    return img


def main():
    res = Path("android/app/src/main/res/drawable")
    (res / "launch_mark.xml").write_text(
        vector(BOX, "Focus ring of the native launch screen (Android 8-11)."),
        encoding="utf-8",
        newline="\n",
    )
    (res / "launch_splash_icon.xml").write_text(
        vector(288, "Android 12+ splash icon: the same 80 dp ring, centred on "
               "the 288 dp icon canvas."),
        encoding="utf-8",
        newline="\n",
    )
    ios = Path("ios/Runner/Assets.xcassets/LaunchImage.imageset")
    for scale, name in ((1, "LaunchImage.png"), (2, "LaunchImage@2x.png"),
                        (3, "LaunchImage@3x.png")):
        png(scale).save(ios / name, optimize=True)


if __name__ == "__main__":
    main()
